export { ConfluenceClient } from './client.js';
export type { AdminKey, CreateAdminKeyData } from './types/admin-key.js';
export type { AppProperty, ListAppPropertiesParams, UpsertAppPropertyData } from './types/app.js';
export type {
  Attachment,
  AttachmentDetailedVersion,
  AttachmentFooterComment,
  AttachmentNestedEnvelope,
  AttachmentOperation,
  AttachmentOperationsResponse,
  AttachmentVersion,
  AttachmentVersionedEntity,
  DeleteAttachmentParams,
  GetAttachmentParams,
  GetAttachmentThumbnailParams,
  ListAllAttachmentsParams,
  ListAttachmentFooterCommentsParams,
  ListAttachmentLabelsParams,
  ListAttachmentVersionsParams,
  ListAttachmentsParams,
  UploadAttachmentResult,
  UploadAttachmentResultItem,
} from './types/attachments.js';
export type {
  BlogPost,
  BlogPostBodyRepresentation,
  BlogPostBodyWriteRepresentation,
  BlogPostContentStatus,
  BlogPostLikeUser,
  BlogPostLikesCount,
  BlogPostLookupStatus,
  BlogPostOperation,
  BlogPostOperationsResponse,
  CreateBlogPostData,
  CreateBlogPostParams,
  DeleteBlogPostParams,
  GetBlogPostClassificationLevelParams,
  GetBlogPostParams,
  ListBlogPostAttachmentsParams,
  ListBlogPostCustomContentParams,
  ListBlogPostFooterCommentsParams,
  ListBlogPostInlineCommentsParams,
  ListBlogPostLabelsParams,
  ListBlogPostLikeUsersParams,
  ListBlogPostVersionsParams,
  ListBlogPostsParams,
  ResetBlogPostClassificationLevelData,
  UpdateBlogPostClassificationLevelData,
  UpdateBlogPostData,
} from './types/blog-posts.js';
export type {
  ClassificationLevel,
  ListClassificationLevelsResponse,
} from './types/classification-levels.js';
export type {
  AttachmentSortOrder,
  AttachmentStatus,
  BlogPostSortOrder,
  BodyFormat,
  CommentSortOrder,
  CommentStatus,
  ConfluenceVersion,
  ContentBody,
  ContentProperty,
  ContentSortOrder,
  CreateContentPropertyData,
  CustomContentSortOrder,
  InlineCommentResolutionStatus,
  Label,
  LabelPrefix,
  LabelSortOrder,
  ListSharedContentPropertiesParams,
  PageSortOrder,
  RedactBlogPostData,
  RedactBlogPostResponse,
  RedactionPointer,
  RedactionPointerResponse,
  SpaceProperty,
  SpaceRoleAssignment,
  SpaceRolePrincipalType,
  SpaceRoleType,
  UpdateCommentData,
  UpdateSharedContentPropertyData,
  VersionSortOrder,
} from './types/common.js';
export type {
  FooterComment,
  FooterCommentChild,
  FooterCommentLike,
  FooterCommentLikeCount,
  FooterCommentOperation,
  FooterCommentOperationsResponse,
  FooterCommentVersionDetail,
  FooterCommentVersionSummary,
  GetFooterCommentParams,
  InlineComment,
  InlineCommentLikeUser,
  InlineCommentLikesCount,
  InlineCommentOperation,
  InlineCommentOperationsResponse,
  InlineCommentSortOrder,
  ListFooterCommentChildrenParams,
  ListFooterCommentLikeUsersParams,
  ListFooterCommentVersionsParams,
  ListFooterCommentsTenantParams,
  ListFooterCommentsParams,
  ListInlineCommentChildrenParams,
  ListInlineCommentLikeUsersParams,
  ListInlineCommentVersionsParams,
  ListInlineCommentsAllParams,
  ListInlineCommentsParams,
  CreateFooterCommentData,
  CreateInlineCommentData,
  UpdateInlineCommentData,
  ContentStatus,
  PrimaryBodyRepresentation,
  PrimaryBodyRepresentationSingle,
  InlineCommentProperties,
  InlineCommentChild,
  CommentVersion,
  DetailedVersion,
  GetInlineCommentParams,
} from './types/comments.js';
export type {
  ListContentPropertiesParams,
  UpdateContentPropertyData,
} from './types/content-properties.js';
export type {
  ConfluenceContentType,
  ConvertContentIdsToTypesData,
  ConvertContentIdsToTypesResponse,
} from './types/content.js';
export type {
  ChildCustomContentSortOrder,
  CreateCustomContentData,
  CustomContent,
  CustomContentBodyRepresentation,
  CustomContentBodyRepresentationSingle,
  CustomContentBodyWrite,
  CustomContentChild,
  CustomContentNestedBodyWrite,
  CustomContentNestedEnvelope,
  CustomContentOperation,
  CustomContentOperationsResponse,
  DeleteCustomContentParams,
  GetCustomContentParams,
  ListCustomContentAttachmentsParams,
  ListCustomContentChildrenParams,
  ListCustomContentFooterCommentsParams,
  ListCustomContentLabelsParams,
  ListCustomContentParams,
  ListCustomContentVersionsParams,
  UpdateCustomContentData,
} from './types/custom-content.js';
export type {
  DataPolicyBodyType,
  DataPolicyMetadata,
  DataPolicySpace,
  DataPolicySpaceDescription,
  DataPolicySpaceFlags,
  DataPolicySpaceIcon,
  DataPolicySpaceLinks,
  DataPolicySpaceSortOrder,
  ListDataPolicySpacesParams,
} from './types/data-policies.js';
export type {
  Database,
  DatabaseAncestor,
  DatabaseAncestorsResponse,
  DatabaseChild,
  DatabaseDescendant,
  DatabaseOperation,
  DatabaseOperationsResponse,
  CreateDatabaseData,
  CreateDatabaseParams,
  GetDatabaseParams,
  ListDatabaseAncestorsParams,
  ListDatabaseChildrenParams,
  ListDatabaseDescendantsParams,
  ListDatabasePropertiesParams,
  ResetDatabaseClassificationLevelData,
  UpdateDatabaseClassificationLevelData,
  UpdateDatabasePropertyData,
} from './types/databases.js';
export type {
  Embed,
  EmbedAncestor,
  EmbedAncestorsResponse,
  EmbedChild,
  EmbedDescendant,
  EmbedOperation,
  EmbedOperationsResponse,
  CreateEmbedData,
  GetEmbedParams,
  ListEmbedAncestorsParams,
  ListEmbedChildrenParams,
  ListEmbedDescendantsParams,
} from './types/embeds.js';
export type {
  Folder,
  FolderAncestor,
  FolderAncestorsResponse,
  FolderChild,
  FolderDescendant,
  FolderOperation,
  FolderOperationsResponse,
  CreateFolderData,
  GetFolderParams,
  ListFolderAncestorsParams,
  ListFolderChildrenParams,
  ListFolderDescendantsParams,
} from './types/folders.js';
export type {
  ListAllLabelsParams,
  ListAttachmentsByLabelParams,
  ListBlogPostsByLabelParams,
  ListLabelsParams,
  ListPagesByLabelParams,
} from './types/labels.js';
export type {
  ChildPage,
  ChildPageSortOrder,
  CreatePageData,
  DeletePageParams,
  GetPageClassificationLevelParams,
  GetPageParams,
  ListChildPagesParams,
  ListPageAncestorsParams,
  ListPageCustomContentParams,
  ListPageDescendantsParams,
  ListPageDirectChildrenParams,
  ListPageFooterCommentsParams,
  ListPageInlineCommentsParams,
  ListPageLikeUsersParams,
  ListPagesParams,
  ListPagesSortOrder,
  Page,
  PageAncestor,
  PageAncestorsResponse,
  PageBodyWriteRepresentation,
  PageChild,
  PageContentStatus,
  PageDescendant,
  PageLikeUser,
  PageLikesCount,
  PageOperation,
  PageOperationsResponse,
  RedactPageData,
  RedactPageResponse,
  ResetPageClassificationLevelData,
  UpdatePageClassificationLevelData,
  UpdatePageData,
  UpdatePageTitleData,
} from './types/pages.js';
export type {
  BulkAssignRolesRequest,
  BulkRemoveAccessRequest,
  BulkTransitionDecodedPermission,
  BulkTransitionPrincipalTypeAssignment,
  BulkTransitionRoleAssignment,
  BulkTransitionSpaceSelection,
  BulkTransitionSpaceTarget,
  BulkTransitionTaskResponse,
  BulkTransitionTaskStatusResponse,
  ListSpacePermissionCombinationsParams,
  ListSpacePermissionCombinationsResponse,
  ListSpacePermissionsParams,
  SpacePermission,
  SpacePermissionCombinationEntry,
} from './types/space-permissions.js';
export type {
  CreateSpaceRoleData,
  DeleteSpaceRoleResponse,
  ListSpaceRolesParams,
  SpaceRole,
  SpaceRoleDetail,
  SpaceRoleMode,
  UpdateSpaceRoleData,
  UpdateSpaceRoleResponse,
} from './types/space-roles.js';
export type {
  CreateSpaceData,
  ListSpaceBlogPostsParams,
  ListSpaceContentLabelsParams,
  ListSpaceCustomContentParams,
  ListSpaceLabelsParams,
  ListSpacePagesParams,
  ListSpacePermissionAssignmentsParams,
  ListSpaceRoleAssignmentsParams,
  ListSpacesParams,
  SetSpaceRoleAssignmentsData,
  SetSpaceRoleAssignmentsResponse,
  Space,
  SpaceContentLabelPrefix,
  SpaceOperation,
  SpaceOperationsResponse,
  SpacePageDepth,
  SpacePermissionAssignment,
  UpdateSpaceDefaultClassificationLevelData,
} from './types/spaces.js';
export type {
  ConfluenceTask,
  GetTaskParams,
  ListTasksParams,
  TaskBodyFormat,
  UpdateTaskData,
  UpdateTaskParams,
} from './types/tasks.js';
export type {
  BulkUsersRequest,
  BulkUsersResponse,
  CheckAccessByEmailResponse,
  CheckAccessOrInviteByEmailRequest,
  ConfluenceAccountStatus,
  ConfluenceAccountType,
  ConfluenceUser,
  ConfluenceUserIcon,
} from './types/users.js';
export type {
  BlogPostVersionItem,
  ContentVersion,
  ListVersionsParams,
  PageVersion,
  VersionedEntity,
} from './types/versions.js';
export type {
  CreateWhiteboardData,
  CreateWhiteboardParams,
  GetWhiteboardParams,
  ListWhiteboardAncestorsParams,
  ListWhiteboardChildrenParams,
  ListWhiteboardDescendantsParams,
  ResetWhiteboardClassificationLevelData,
  UpdateWhiteboardClassificationLevelData,
  Whiteboard,
  WhiteboardAncestor,
  WhiteboardAncestorsResponse,
  WhiteboardChild,
  WhiteboardDescendant,
  WhiteboardLocale,
  WhiteboardOperation,
  WhiteboardOperationsResponse,
  WhiteboardTemplateKey,
  WhiteboardVersion,
} from './types/whiteboards.js';
export type { CursorPaginatedResponse } from '../core/pagination.js';
export { PagesResource } from './resources/pages.js';
export { SpacesResource } from './resources/spaces.js';
export { BlogPostsResource } from './resources/blog-posts.js';
export { CommentsResource } from './resources/comments.js';
export { AttachmentsResource } from './resources/attachments.js';
export { LabelsResource } from './resources/labels.js';
export { ContentPropertiesResource } from './resources/content-properties.js';
export { CustomContentResource } from './resources/custom-content.js';
export { WhiteboardsResource } from './resources/whiteboards.js';
export { TasksResource } from './resources/tasks.js';
export { VersionsResource } from './resources/versions.js';
export { AppResource } from './resources/app.js';
export { ClassificationLevelsResource } from './resources/classification-levels.js';
export { ContentResource } from './resources/content.js';
export { DataPoliciesResource } from './resources/data-policies.js';
export { DatabasesResource } from './resources/databases.js';
export { EmbedsResource } from './resources/embeds.js';
export { FoldersResource } from './resources/folders.js';
export { FooterCommentsResource } from './resources/footer-comments.js';
export { InlineCommentsResource } from './resources/inline-comments.js';
export { SpacePermissionsResource } from './resources/space-permissions.js';
export { SpaceRoleModeResource } from './resources/space-role-mode.js';
export { SpaceRolesResource } from './resources/space-roles.js';
export { UsersResource } from './resources/users.js';
export { UsersBulkResource } from './resources/users-bulk.js';
export { AdminKeyResource } from './resources/admin-key.js';
