export { ConfluenceClient } from './client.js';
export type {
  Page,
  Space,
  BlogPost,
  FooterComment,
  InlineComment,
  Attachment,
  AttachmentDetailedVersion,
  AttachmentFooterComment,
  AttachmentNestedEnvelope,
  AttachmentOperation,
  AttachmentOperationsResponse,
  AttachmentStatus,
  AttachmentVersion,
  AttachmentVersionedEntity,
  DeleteAttachmentParams,
  GetAttachmentParams,
  Label,
  LabelPrefix,
  ConfluenceVersion,
  BodyFormat,
  ContentBody,
  ListPagesParams,
  GetPageParams,
  CreatePageData,
  UpdatePageData,
  DeletePageParams,
  ListSpacesParams,
  ListBlogPostsParams,
  CreateBlogPostData,
  UpdateBlogPostData,
  ListFooterCommentsParams,
  CreateFooterCommentData,
  UpdateCommentData,
  ListInlineCommentsParams,
  CreateInlineCommentData,
  ListAttachmentsParams,
  ListAllAttachmentsParams,
  ListAttachmentFooterCommentsParams,
  ListAttachmentLabelsParams,
  ListAttachmentVersionsParams,
  ListLabelsParams,
  LabelSortOrder,
  ListAllLabelsParams,
  AttachmentSortOrder,
  ListAttachmentsByLabelParams,
  BlogPostSortOrder,
  ListBlogPostsByLabelParams,
  PageSortOrder,
  ListPagesByLabelParams,
  ContentProperty,
  ListContentPropertiesParams,
  ListSharedContentPropertiesParams,
  CreateContentPropertyData,
  UpdateContentPropertyData,
  UpdateSharedContentPropertyData,
  CustomContent,
  CustomContentBodyRepresentation,
  CustomContentBodyRepresentationSingle,
  CustomContentBodyWrite,
  CustomContentChild,
  CustomContentNestedBodyWrite,
  CustomContentNestedEnvelope,
  CustomContentOperation,
  CustomContentOperationsResponse,
  ChildCustomContentSortOrder,
  ListCustomContentParams,
  ListCustomContentAttachmentsParams,
  ListCustomContentChildrenParams,
  ListCustomContentFooterCommentsParams,
  ListCustomContentLabelsParams,
  ListCustomContentVersionsParams,
  GetCustomContentParams,
  DeleteCustomContentParams,
  CreateCustomContentData,
  UpdateCustomContentData,
  GetAttachmentThumbnailParams,
  Whiteboard,
  CreateWhiteboardData,
  CreateWhiteboardParams,
  GetWhiteboardParams,
  WhiteboardAncestor,
  WhiteboardAncestorsResponse,
  ListWhiteboardAncestorsParams,
  WhiteboardDescendant,
  ListWhiteboardDescendantsParams,
  WhiteboardChild,
  ListWhiteboardChildrenParams,
  WhiteboardLocale,
  WhiteboardOperation,
  WhiteboardOperationsResponse,
  WhiteboardTemplateKey,
  WhiteboardVersion,
  UpdateWhiteboardClassificationLevelData,
  ResetWhiteboardClassificationLevelData,
  ConfluenceTask,
  ListTasksParams,
  GetTaskParams,
  UpdateTaskData,
  ContentVersion,
  ListVersionsParams,
  AppProperty,
  ListAppPropertiesParams,
  UpsertAppPropertyData,
  ClassificationLevel,
  ListClassificationLevelsResponse,
  ConfluenceContentType,
  ConvertContentIdsToTypesData,
  ConvertContentIdsToTypesResponse,
  DataPolicyMetadata,
  DataPolicySpace,
  DataPolicySpaceFlags,
  DataPolicySpaceSortOrder,
  ListDataPolicySpacesParams,
  Database,
  CreateDatabaseData,
  CreateDatabaseParams,
  GetDatabaseParams,
  DatabaseAncestor,
  DatabaseAncestorsResponse,
  ListDatabaseAncestorsParams,
  DatabaseDescendant,
  ListDatabaseDescendantsParams,
  DatabaseChild,
  ListDatabaseChildrenParams,
  ContentSortOrder,
  DatabaseOperation,
  DatabaseOperationsResponse,
  ListDatabasePropertiesParams,
  UpdateDatabasePropertyData,
  UpdateDatabaseClassificationLevelData,
  ResetDatabaseClassificationLevelData,
  Folder,
  CreateFolderData,
  GetFolderParams,
  FolderAncestor,
  FolderAncestorsResponse,
  ListFolderAncestorsParams,
  FolderDescendant,
  ListFolderDescendantsParams,
  FolderChild,
  ListFolderChildrenParams,
  FolderOperation,
  FolderOperationsResponse,
  Embed,
  CreateEmbedData,
  GetEmbedParams,
  EmbedAncestor,
  EmbedAncestorsResponse,
  ListEmbedAncestorsParams,
  EmbedDescendant,
  ListEmbedDescendantsParams,
  EmbedChild,
  ListEmbedChildrenParams,
  EmbedOperation,
  EmbedOperationsResponse,
  CommentSortOrder,
  VersionSortOrder,
  ListFooterCommentsTenantParams,
  GetFooterCommentParams,
  ListFooterCommentChildrenParams,
  FooterCommentChild,
  FooterCommentLikeCount,
  FooterCommentLike,
  ListFooterCommentLikeUsersParams,
  FooterCommentOperation,
  FooterCommentOperationsResponse,
  ListFooterCommentVersionsParams,
  FooterCommentVersionSummary,
  FooterCommentVersionDetail,
  InlineCommentSortOrder,
  ListInlineCommentsAllParams,
  ListInlineCommentChildrenParams,
  ListInlineCommentLikeUsersParams,
  ListInlineCommentVersionsParams,
  UpdateInlineCommentData,
  InlineCommentLikesCount,
  InlineCommentLikeUser,
  InlineCommentOperation,
  InlineCommentOperationsResponse,
  SpacePermission,
  ListSpacePermissionsParams,
  SpaceRoleMode,
  SpaceRole,
  SpaceRoleDetail,
  SpaceRoleType,
  SpaceRolePrincipalType,
  ListSpaceRolesParams,
  CreateSpaceRoleData,
  UpdateSpaceRoleData,
  UpdateSpaceRoleResponse,
  DeleteSpaceRoleResponse,
  ConfluenceUser,
  ConfluenceUserIcon,
  ConfluenceAccountStatus,
  ConfluenceAccountType,
  BulkUsersRequest,
  BulkUsersResponse,
  CheckAccessOrInviteByEmailRequest,
  CheckAccessByEmailResponse,
  // Blog post sub-resources (B066-B084)
  GetBlogPostParams,
  BlogPostBodyRepresentation,
  BlogPostLookupStatus,
  ListBlogPostAttachmentsParams,
  ListBlogPostFooterCommentsParams,
  ListBlogPostInlineCommentsParams,
  CommentStatus,
  InlineCommentResolutionStatus,
  ListBlogPostLabelsParams,
  CustomContentSortOrder,
  ListBlogPostCustomContentParams,
  ListBlogPostLikeUsersParams,
  ListBlogPostVersionsParams,
  GetBlogPostClassificationLevelParams,
  BlogPostLikesCount,
  BlogPostLikeUser,
  BlogPostOperation,
  BlogPostOperationsResponse,
  UpdateBlogPostClassificationLevelData,
  ResetBlogPostClassificationLevelData,
  RedactBlogPostData,
  RedactionPointer,
  RedactBlogPostResponse,
  RedactionPointerResponse,
  // Page sub-resources (B170-B188 + B895)
  PageAncestor,
  PageAncestorsResponse,
  ListPageAncestorsParams,
  PageDescendant,
  ListPageDescendantsParams,
  PageChild,
  ListPageDirectChildrenParams,
  ChildPageSortOrder,
  ChildPage,
  ListChildPagesParams,
  ListPageCustomContentParams,
  GetPageClassificationLevelParams,
  UpdatePageClassificationLevelData,
  ResetPageClassificationLevelData,
  PageLikesCount,
  PageLikeUser,
  ListPageLikeUsersParams,
  PageOperation,
  PageOperationsResponse,
  RedactPageData,
  RedactPageResponse,
  UpdatePageTitleData,
  ListPageFooterCommentsParams,
  ListPageInlineCommentsParams,
} from './types.js';
export type { CursorPaginatedResponse } from '../core/pagination.js';
export { PagesResource } from './resources/pages.js';
export { SpacesResource } from './resources/spaces.js';
export { BlogPostsResource } from './resources/blog-posts.js';
export { CommentsResource } from './resources/comments.js';
export { AttachmentsResource } from './resources/attachments.js';
export { LabelsResource } from './resources/labels.js';
export { ContentPropertiesResource } from './resources/content-properties.js';
export { CustomContentResource } from './resources/custom-content.js';
export { WhiteboardsResource } from './resources/whiteboards.js';
export { TasksResource } from './resources/tasks.js';
export { VersionsResource } from './resources/versions.js';
export { AppResource } from './resources/app.js';
export { ClassificationLevelsResource } from './resources/classification-levels.js';
export { ContentResource } from './resources/content.js';
export { DataPoliciesResource } from './resources/data-policies.js';
export { DatabasesResource } from './resources/databases.js';
export { EmbedsResource } from './resources/embeds.js';
export { FoldersResource } from './resources/folders.js';
export { FooterCommentsResource } from './resources/footer-comments.js';
export { InlineCommentsResource } from './resources/inline-comments.js';
export { SpacePermissionsResource } from './resources/space-permissions.js';
export { SpaceRoleModeResource } from './resources/space-role-mode.js';
export { SpaceRolesResource } from './resources/space-roles.js';
export { UsersResource } from './resources/users.js';
export { UsersBulkResource } from './resources/users-bulk.js';
