// Core errors
export {
  AtlassianError,
  HttpError,
  AuthenticationError,
  ForbiddenError,
  NotFoundError,
  RateLimitError,
  TimeoutError,
  NetworkError,
  ValidationError,
  PaginationError,
  ResponseTooLargeError,
  CircuitBreakerOpenError,
  RateLimiterExhaustedError,
  OAuthError,
} from './core/index.js';

// Core types
export type {
  ClientConfig,
  AuthConfig,
  BasicAuthConfig,
  BearerAuthConfig,
  RequestOptions,
  ApiResponse,
  RateLimitInfo,
  Transport,
  Logger,
  Middleware,
  RequestIdOptions,
} from './core/index.js';

// Core config and transport
export { resolveConfig, HttpTransport } from './core/index.js';

// Retry primitives (reuse HttpTransport's retry semantics in custom transports)
export { executeWithRetry } from './core/index.js';
export type { RetryConfig } from './core/index.js';

// Middleware composition (matches HttpTransport's internal composition)
export { createMiddlewareChain } from './core/index.js';

// Pagination helpers (cursor / offset / search)
export { extractCursor, paginateCursor, paginateOffset, paginateSearch } from './core/index.js';
export type { PaginateOptions, SearchPaginatedResponse } from './core/index.js';

// Response serialisation helper
export { toJSON } from './core/index.js';
export type { SerializableApiResponse } from './core/index.js';

// OAuth 2.0 token refresh
export { createOAuthRefreshMiddleware, fetchRefreshedTokens } from './core/index.js';
export type { OAuthRefreshConfig, OAuthTokens } from './core/index.js';

// Atlassian Connect JWT
export {
  createConnectJwtMiddleware,
  signConnectJwt,
  computeQsh,
  verifyConnectAsymmetricJwt,
} from './core/index.js';
export type { ConnectJwtConfig, AsymmetricJwtVerifyOptions } from './core/index.js';

// Response caching
export { createCacheMiddleware } from './core/index.js';
export type { CacheOptions } from './core/index.js';

// Request batching (deduplication)
export { createBatchMiddleware } from './core/index.js';

// Circuit breaker
export { createCircuitBreakerMiddleware } from './core/index.js';
export type { CircuitBreakerOptions } from './core/index.js';

// Proactive token-bucket rate limiter (B017)
export { createRateLimiterMiddleware } from './core/index.js';
export type { RateLimiterOptions } from './core/index.js';

// OAuth scope detection
export { detectRequiredScopes, listKnownOperations } from './core/index.js';
export type { AtlassianScope } from './core/index.js';

// OpenAPI type generation
export { generateTypes } from './core/index.js';
export type { OpenApiSpec, OpenApiSchemaObject, GeneratedTypes } from './core/index.js';

// Confluence
export { ConfluenceClient } from './confluence/index.js';
export type {
  Page,
  Space,
  BlogPost,
  FooterComment,
  InlineComment,
  Attachment,
  AttachmentDetailedVersion,
  AttachmentFooterComment,
  AttachmentNestedEnvelope,
  AttachmentOperation,
  AttachmentOperationsResponse,
  AttachmentStatus,
  AttachmentVersion,
  AttachmentVersionedEntity,
  DeleteAttachmentParams,
  GetAttachmentParams,
  Label,
  LabelPrefix,
  ConfluenceVersion,
  ListPagesParams,
  GetPageParams,
  CreatePageData,
  UpdatePageData,
  DeletePageParams,
  ListSpacesParams,
  ListBlogPostsParams,
  CreateBlogPostData,
  UpdateBlogPostData,
  ListFooterCommentsParams,
  CreateFooterCommentData,
  UpdateCommentData,
  ListInlineCommentsParams,
  CreateInlineCommentData,
  ListAttachmentsParams,
  ListAllAttachmentsParams,
  ListAttachmentFooterCommentsParams,
  ListAttachmentLabelsParams,
  ListAttachmentVersionsParams,
  ListLabelsParams,
  ListLabelsParams as ConfluenceListLabelsParams,
  LabelSortOrder,
  ListAllLabelsParams,
  AttachmentSortOrder as ConfluenceAttachmentSortOrder,
  ListAttachmentsByLabelParams,
  BlogPostSortOrder as ConfluenceBlogPostSortOrder,
  ListBlogPostsByLabelParams,
  PageSortOrder as ConfluencePageSortOrder,
  ListPagesByLabelParams,
  CursorPaginatedResponse,
  ContentProperty,
  ListContentPropertiesParams,
  ListSharedContentPropertiesParams,
  CreateContentPropertyData,
  UpdateContentPropertyData,
  UpdateSharedContentPropertyData,
  CustomContent,
  CustomContentBodyRepresentation,
  CustomContentBodyRepresentationSingle,
  CustomContentBodyWrite,
  CustomContentChild,
  CustomContentNestedBodyWrite,
  CustomContentNestedEnvelope,
  CustomContentOperation,
  CustomContentOperationsResponse,
  ChildCustomContentSortOrder,
  ListCustomContentParams,
  ListCustomContentAttachmentsParams,
  ListCustomContentChildrenParams,
  ListCustomContentFooterCommentsParams,
  ListCustomContentLabelsParams,
  ListCustomContentVersionsParams,
  GetCustomContentParams,
  DeleteCustomContentParams,
  CreateCustomContentData,
  UpdateCustomContentData,
  GetAttachmentThumbnailParams,
  Whiteboard,
  CreateWhiteboardData,
  CreateWhiteboardParams,
  GetWhiteboardParams,
  WhiteboardAncestor,
  WhiteboardAncestorsResponse,
  ListWhiteboardAncestorsParams,
  WhiteboardDescendant,
  ListWhiteboardDescendantsParams,
  WhiteboardChild,
  ListWhiteboardChildrenParams,
  WhiteboardLocale,
  WhiteboardOperation,
  WhiteboardOperationsResponse,
  WhiteboardTemplateKey,
  WhiteboardVersion,
  UpdateWhiteboardClassificationLevelData,
  ResetWhiteboardClassificationLevelData,
  ConfluenceTask,
  ListTasksParams as ConfluenceListTasksParams,
  GetTaskParams,
  UpdateTaskData,
  ContentVersion,
  ListVersionsParams,
  ClassificationLevel,
  ListClassificationLevelsResponse,
  ConfluenceContentType,
  ConvertContentIdsToTypesData,
  ConvertContentIdsToTypesResponse,
  DataPolicyMetadata,
  DataPolicySpace,
  DataPolicySpaceFlags,
  DataPolicySpaceSortOrder,
  ListDataPolicySpacesParams,
  Database,
  CreateDatabaseData,
  CreateDatabaseParams,
  GetDatabaseParams,
  DatabaseAncestor,
  DatabaseAncestorsResponse,
  ListDatabaseAncestorsParams,
  DatabaseDescendant,
  ListDatabaseDescendantsParams,
  DatabaseChild,
  ListDatabaseChildrenParams,
  ContentSortOrder,
  DatabaseOperation,
  DatabaseOperationsResponse,
  ListDatabasePropertiesParams,
  UpdateDatabasePropertyData,
  UpdateDatabaseClassificationLevelData,
  ResetDatabaseClassificationLevelData,
  Folder,
  CreateFolderData,
  GetFolderParams,
  FolderAncestor,
  FolderAncestorsResponse,
  ListFolderAncestorsParams,
  FolderDescendant,
  ListFolderDescendantsParams,
  FolderChild,
  ListFolderChildrenParams,
  FolderOperation,
  FolderOperationsResponse,
  Embed,
  CreateEmbedData,
  GetEmbedParams,
  EmbedAncestor,
  EmbedAncestorsResponse,
  ListEmbedAncestorsParams,
  EmbedDescendant,
  ListEmbedDescendantsParams,
  EmbedChild,
  ListEmbedChildrenParams,
  EmbedOperation,
  EmbedOperationsResponse,
  CommentSortOrder,
  VersionSortOrder,
  ListFooterCommentsTenantParams,
  GetFooterCommentParams,
  ListFooterCommentChildrenParams,
  FooterCommentChild,
  FooterCommentLikeCount,
  FooterCommentLike,
  ListFooterCommentLikeUsersParams,
  FooterCommentOperation,
  FooterCommentOperationsResponse,
  ListFooterCommentVersionsParams,
  FooterCommentVersionSummary,
  FooterCommentVersionDetail,
  InlineCommentSortOrder,
  ListInlineCommentsAllParams,
  ListInlineCommentChildrenParams,
  ListInlineCommentLikeUsersParams,
  ListInlineCommentVersionsParams,
  UpdateInlineCommentData,
  InlineCommentLikesCount,
  InlineCommentLikeUser,
  InlineCommentOperation,
  InlineCommentOperationsResponse,
  SpacePermission,
  ListSpacePermissionsParams,
  BulkRemoveAccessRequest,
  BulkAssignRolesRequest,
  BulkTransitionDecodedPermission,
  BulkTransitionPrincipalTypeAssignment,
  BulkTransitionRoleAssignment,
  BulkTransitionSpaceSelection,
  BulkTransitionSpaceTarget,
  BulkTransitionTaskResponse,
  BulkTransitionTaskStatusResponse,
  ListSpacePermissionCombinationsParams,
  ListSpacePermissionCombinationsResponse,
  SpacePermissionCombinationEntry,
  SpaceRoleMode,
  SpaceRole,
  SpaceRoleDetail,
  SpaceRoleType,
  SpaceRolePrincipalType,
  ListSpaceRolesParams,
  CreateSpaceRoleData,
  UpdateSpaceRoleData,
  UpdateSpaceRoleResponse,
  DeleteSpaceRoleResponse,
  ConfluenceUser,
  ConfluenceUserIcon,
  ConfluenceAccountStatus,
  ConfluenceAccountType,
  BulkUsersRequest,
  BulkUsersResponse,
  CheckAccessOrInviteByEmailRequest,
  CheckAccessByEmailResponse,
  // Blog post sub-resources (B066-B084)
  GetBlogPostParams,
  BlogPostBodyRepresentation,
  BlogPostLookupStatus,
  ListBlogPostAttachmentsParams,
  ListBlogPostFooterCommentsParams,
  ListBlogPostInlineCommentsParams,
  CommentStatus,
  InlineCommentResolutionStatus,
  ListBlogPostLabelsParams,
  CustomContentSortOrder,
  ListBlogPostCustomContentParams,
  ListBlogPostLikeUsersParams,
  ListBlogPostVersionsParams,
  GetBlogPostClassificationLevelParams,
  BlogPostLikesCount,
  BlogPostLikeUser,
  BlogPostOperation,
  BlogPostOperationsResponse,
  UpdateBlogPostClassificationLevelData,
  ResetBlogPostClassificationLevelData,
  RedactBlogPostData,
  RedactionPointer,
  RedactBlogPostResponse,
  RedactionPointerResponse,
  // Page sub-resources (B170-B188 + B895)
  PageAncestor,
  PageAncestorsResponse,
  ListPageAncestorsParams,
  PageDescendant,
  ListPageDescendantsParams,
  PageChild,
  ListPageDirectChildrenParams,
  ChildPageSortOrder,
  ChildPage,
  ListChildPagesParams,
  ListPageCustomContentParams,
  GetPageClassificationLevelParams,
  UpdatePageClassificationLevelData,
  ResetPageClassificationLevelData,
  PageLikesCount,
  PageLikeUser,
  ListPageLikeUsersParams,
  PageOperation,
  PageOperationsResponse,
  RedactPageData,
  RedactPageResponse,
  UpdatePageTitleData,
  ListPageFooterCommentsParams,
  ListPageInlineCommentsParams,
  // Spaces sub-resources (B196-B213)
  CreateSpaceData,
  SpaceRoleAssignment,
  ListSpaceBlogPostsParams,
  SpaceContentLabelPrefix,
  ListSpaceContentLabelsParams,
  ListSpaceLabelsParams,
  ListSpaceCustomContentParams,
  SpaceOperation,
  SpaceOperationsResponse,
  SpacePageDepth,
  ListSpacePagesParams,
  SpacePermissionAssignment,
  ListSpacePermissionAssignmentsParams,
  ListSpaceRoleAssignmentsParams,
  SetSpaceRoleAssignmentsData,
  UpdateSpaceDefaultClassificationLevelData,
} from './confluence/index.js';

// Jira
export { JiraClient } from './jira/index.js';
export type {
  Issue,
  CreatedIssue,
  Project,
  User,
  IssueType,
  Priority,
  Status,
  Transition,
  SearchResult,
  GetIssueParams,
  CreateIssueData,
  UpdateIssueData,
  TransitionData,
  ListProjectsParams,
  SearchParams,
  SearchUsersParams,
  OffsetPaginatedResponse,
  IssueComment,
  IssueAttachment,
  JiraLabel,
  ListIssueCommentsParams,
  CreateIssueCommentData,
  UpdateIssueCommentData,
  ListLabelsParams as JiraListLabelsParams,
  Board,
  BoardIssue,
  ListBoardsParams,
  ListBoardIssuesParams,
  Sprint,
  CreateSprintData,
  UpdateSprintData,
  ListSprintIssuesParams,
  Workflow,
  WorkflowTransition,
  WorkflowStatus,
  ListWorkflowsParams,
  Dashboard,
  DashboardSharePermission,
  ListDashboardsParams,
  CreateDashboardData,
  UpdateDashboardData,
  Filter,
  FilterSharePermission,
  ListFiltersParams,
  CreateFilterData,
  UpdateFilterData,
  Field,
  CreateFieldData,
  UpdateFieldData,
  ListFieldsParams,
  Webhook,
  RegisterWebhookData,
  RegisteredWebhooks,
  ListWebhooksParams,
  JqlAutocompleteData,
  ParseJqlQueriesData,
  ParsedJqlQueries,
  SanitizeJqlQueriesData,
  SanitizedJqlQueries,
  JqlSuggestionsParams,
  JqlSuggestions,
  BulkCreateIssueData,
  BulkCreatedIssues,
  BulkSetIssuePropertyData,
  BulkDeleteIssuePropertyData,
  BulkIssueIsWatchingResult,
} from './jira/index.js';
